// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/08/2025, 11:51:12
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/alexandre/Documentos/rainbowtrack/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/alexandre/Documentos/rainbowtrack/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/alexandre/Documentos/rainbowtrack/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/alexandre/Documentos/rainbowtrack/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/alexandre/Documentos/rainbowtrack/plugins/**/*.{js,ts,mjs}","/home/alexandre/Documentos/rainbowtrack/composables/**/*.{js,ts,mjs}","/home/alexandre/Documentos/rainbowtrack/utils/**/*.{js,ts,mjs}","/home/alexandre/Documentos/rainbowtrack/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/alexandre/Documentos/rainbowtrack/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/alexandre/Documentos/rainbowtrack/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/alexandre/Documentos/rainbowtrack/app.config.{js,ts,mjs}","/home/alexandre/Documentos/rainbowtrack/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;